# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cbacd629a3d31aa25a4454e059b16f352b0f020fc41e46bd2c8187b1effdf609b4045b0b1c647cbcc08fba956b161dbe725427a47406de44579ba2c1f2e890b

test:
  secret_key_base: 756ef7939aab24f107a57d86146d408ca6fbcde6252e6ad7e892382155447c02d01f76e5830435c4b9df0565f83a4234990e66e8198c6e4a8c3da95c4d6b545f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
